# -*- coding: utf-8 -*-
"""app (5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojaf42sxq-U1AI4-Q3ebMvL_1Du2pJlo

# app.py

Original file: `app.py`. The Flask application entry point. Expects HeartGuard_Final_Model.pkl in the working directory, and heartguard_transformers.py, heartguard_db.py, and heartguard_knowledge.py present alongside it.

**PDF generation has been fully removed** for deployment simplification: the `/report/<patient_id>` route, the `heartguard_report` import, `send_file`, and all report/PDF-output-path handling are gone. `_score_single()` no longer computes a separate uncapped `top_features_full` list (that existed solely to feed the PDF's full factor list) -- there's now a single `top_features` list, filtered and capped for the UI. `/predict` (inference + trend-aware, Grok-enhanced-or-baseline clinical advice) is otherwise unchanged and fully intact, as are `/history/<patient_id>` and `/health`. `heartguard_report.py` has been deleted from the project entirely -- see requirements.txt for the corresponding dependency cleanup (fpdf2 removed).

**Heart Age has been removed** for this production release: the `HeartGuard_Heart_Age_Model.pkl` load, `heart_age_model`, `heart_age_features`, the Heart Age prediction step in `_score_single()`, and the `heart_age` field in the `/predict` JSON response are all gone. All other prediction logic (SHAP, Top Features, Trend, History, Specialist Recommendation, Action Plan, Missing Labs) is unchanged.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
import warnings
try:
    from sklearn.exceptions import InconsistentVersionWarning
    warnings.filterwarnings("ignore", category=InconsistentVersionWarning)
except ImportError:
    pass

# Must be imported BEFORE joblib.load(): IterativeImputer is gated behind
# this experimental-enable flag, and unpickling the saved pipeline requires
# sklearn.impute.IterativeImputer to already be resolvable on the module.
from sklearn.experimental import enable_iterative_imputer  # noqa: F401
from sklearn.impute import IterativeImputer  # noqa: F401

# Required so joblib can unpickle the imblearn.pipeline.Pipeline / SMOTEENN
# objects embedded in HeartGuard_Final_Model.pkl. SMOTEENN itself is
# automatically skipped at predict()/predict_proba() time by imblearn's
# Pipeline, but the package must still be importable to reconstruct it.
import imblearn  # noqa: F401

import numpy as np
import pandas as pd
import joblib
import shap
from flask import Flask, request, jsonify

# Must be imported so joblib can resolve ClinicalFeatureEngineer /
# CategoricalRounder when unpickling HeartGuard_Final_Model.pkl.
# heartguard_transformers.py must sit next to app.py.
from heartguard_transformers import transform_for_shap, get_risk_band, FEATURE_ORDER, OPTIONAL_LAB_COLS
import heartguard_db as db
from heartguard_knowledge import (
    FEATURE_EXPLANATIONS,
    SPECIALIST_MAP,
    filter_non_modifiable,
    get_clinical_advice,
    get_risk_trend_sentiment,
)

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Load artifacts once at startup. Fail loudly and immediately if anything is
# missing/incompatible -- a broken model should never silently serve wrong
# predictions.
# ---------------------------------------------------------------------------
import os
pkl_path = "HeartGuard_Final_Model.pkl"
if not os.path.exists(pkl_path) and os.path.exists("HeartGuard_Final_Model (1).pkl"):
    pkl_path = "HeartGuard_Final_Model (1).pkl"
model_package = joblib.load(pkl_path)
model = model_package["model"]
threshold = model_package["threshold"]
feature_columns = model_package["feature_columns"]

# SHAP explainer is rebuilt from the already-loaded classifier at startup
# rather than pickled separately -- TreeExplainer objects are cheap to build
# and this avoids any SHAP-version pickling fragility.
_classifier = model.named_steps["classifier"]
explainer = shap.TreeExplainer(_classifier)

db.init_db()

TOP_N_FEATURES_UI = 5  # UI shows the top 3-5 actionable factors (upper bound)
SHAP_SIGNIFICANCE_THRESHOLD = 0.01  # ignore near-zero log-odds contributions

# Midpoint (in years) for each categorical age-range string the UI may send
# for AgeCategory. The pipeline was fit on a numeric AgeCategory, so any
# categorical value coming from the UI must be converted before it reaches
# the model -- see map_age_to_numeric() and its use in _prepare_input().
AGE_CATEGORY_MIDPOINTS = {
    "18-24": 21,
    "25-29": 27,
    "30-34": 32,
    "35-39": 37,
    "40-44": 42,
    "45-49": 47,
    "50-54": 52,
    "55-59": 57,
    "60-64": 62,
    "65-69": 67,
    "70-74": 72,
    "75-79": 77,
    "80+": 85,  # open-ended top bucket; 85 used as a representative midpoint
}


def map_age_to_numeric(age_category):
    """
    Converts a categorical age-range string from the UI (e.g. '45-49') into
    its numeric midpoint (47.0) for the model pipeline, which expects
    AgeCategory as a numeric value rather than a range label.

    Raises ValueError on an unrecognized category so a bad/typo'd UI value
    surfaces as a clear 400 response (via _prepare_input's existing
    ValueError -> 400 handling) instead of silently reaching the model as
    NaN or a raw string.
    """
    if age_category not in AGE_CATEGORY_MIDPOINTS:
        raise ValueError(f"Unrecognized AgeCategory value: {age_category!r}")
    return float(AGE_CATEGORY_MIDPOINTS[age_category])


def _get_ranked_shap_features(shap_row):
    """
    Ranks ALL features by |SHAP value| and returns every one whose
    magnitude clears SHAP_SIGNIFICANCE_THRESHOLD, highest impact first, as
    a list of {"feature", "shap_value", "explanation"} dicts.

    Deliberately uncapped: non-modifiable demographic features (age, sex,
    race) still need to be filtered out afterward, and filtering can only
    pull in replacements from further down the ranking if this list isn't
    already truncated. Callers apply heartguard_knowledge.filter_non_modifiable()
    and then cap the result at TOP_N_FEATURES_UI for on-screen display.
    """
    ranked_idx = np.argsort(-np.abs(shap_row))
    results = []
    for idx in ranked_idx:
        value = float(shap_row[idx])
        if abs(value) < SHAP_SIGNIFICANCE_THRESHOLD:
            continue
        feature = FEATURE_ORDER[idx]
        results.append({
            "feature": feature,
            "shap_value": round(value, 4),
            "explanation": FEATURE_EXPLANATIONS.get(
                feature, "This factor contributes to overall cardiovascular risk."
            ),
        })
    return results


def _prepare_input(payload):
    """
    Builds a DataFrame in the exact column order the pipeline was fit on.
    Accepts a single record {...} or a batch [{...}, {...}]. Raises
    ValueError with a clear message on missing required fields -- callers
    turn this into a 400 response.

    OPTIONAL LAB TESTS: SystolicBP, DiastolicBP, BloodSugar, Cholesterol,
    and HbA1c may be omitted entirely (or sent as null) if the test wasn't
    performed. ClinicalFeatureEngineer fills a skipped test with a fixed
    clinical "normal range" value and raises a companion Missing_Flag_<col>
    so the model discounts the assumed value rather than treating it as an
    observed result. Every other field is still required.
    """
    records = payload if isinstance(payload, list) else [payload]
    input_df = pd.DataFrame(records)

    # UI PREPROCESSING: the UI sends AgeCategory as a range label (e.g.
    # '45-49'), but the pipeline was fit on its numeric midpoint. Convert
    # here, before any downstream validation/scoring touches this column,
    # so the DataFrame returned by this function is always pipeline-ready.
    # Already-numeric values (e.g. a caller that bypasses the UI and sends
    # the midpoint directly) pass through unchanged.
    if "AgeCategory" in input_df.columns:
        input_df["AgeCategory"] = input_df["AgeCategory"].apply(
            lambda v: map_age_to_numeric(v) if isinstance(v, str) else v
        )

    required_columns = [c for c in feature_columns if c not in OPTIONAL_LAB_COLS]
    missing = [c for c in required_columns if c not in input_df.columns]
    if missing:
        raise ValueError(f"Missing required fields: {missing}")

    # Optional lab tests may be absent from the payload entirely (as
    # opposed to present-but-null) -- add them as an all-NaN column so
    # ClinicalFeatureEngineer's missing-flag/normal-range logic sees them
    # as skipped, same as an explicit null would.
    for col in OPTIONAL_LAB_COLS:
        if col not in input_df.columns:
            input_df[col] = np.nan

    # INPUT VALIDATION NOTE: 'Sex' must use the dataset's raw codes
    # (1=Male, 2=Female). ClinicalFeatureEngineer remaps these internally;
    # pre-encoded 0/1 values will be silently (mis)remapped.
    return input_df[feature_columns], (payload if isinstance(payload, list) else records)


def _get_previous_probability(patient_id):
    """
    Looks up the patient's most recent *already-stored* probability, before
    the current prediction is saved. Must always be called BEFORE
    db.save_prediction() for this patient/request, otherwise the value just
    about to be saved would be mistaken for history.

    Returns None for first-time patients / no prior history -- this is the
    single source of truth for "no history yet" and is safe to hand
    straight to heartguard_knowledge.get_clinical_advice() /
    get_risk_trend_sentiment(), both of which treat None as "omit the trend
    entirely" rather than raising.
    """
    history = db.get_history(patient_id, limit=2)
    return history[0]["probability"] if history else None


def _score_single(row_df):
    """
    Runs one already-column-ordered single-row DataFrame through the full
    ML pipeline and returns every derived clinical output as a dict.

    Deliberately has no knowledge of trend/history/action-plan data: this
    function is pure model inference plus feature filtering, so it can be
    called before the caller decides whether/how to touch heartguard_db.
    Callers layer the trend-aware clinical advice on top via
    _build_clinical_advice() once they've fetched previous_probability and
    the current trend.

    Returns "top_features": the SHAP-ranked feature list with
    non-modifiable demographic factors (age, sex, race) filtered out and
    capped at TOP_N_FEATURES_UI, for on-screen display. May be shorter
    than expected (even empty) if few features clear the significance
    threshold or most of the top drivers happen to be non-modifiable --
    callers handle that gracefully.
    """
    y_prob = float(model.predict_proba(row_df)[:, 1][0])
    y_pred = int(y_prob >= threshold)
    risk_band = get_risk_band(y_prob)

    shap_ready = transform_for_shap(model, row_df)
    shap_row = np.asarray(explainer.shap_values(shap_ready))[0]

    ranked_features = _get_ranked_shap_features(shap_row)
    for f in ranked_features:
        f["value"] = float(shap_ready[0, FEATURE_ORDER.index(f["feature"])])
    modifiable_features = filter_non_modifiable(ranked_features)
    ui_top_features = modifiable_features[:TOP_N_FEATURES_UI]

    # Which optional lab tests were actually skipped for this patient, read
    # straight off the transformed feature array (the same Missing_Flag_*
    # values the classifier itself was scored on) rather than re-inspecting
    # the raw payload, so this can never drift out of sync with the model.
    missing_labs = sorted(
        lab for lab in OPTIONAL_LAB_COLS
        if shap_ready[0, FEATURE_ORDER.index(f"Missing_Flag_{lab}")] >= 0.5
    )

    specialist = SPECIALIST_MAP.get(
        ui_top_features[0]["feature"], "General Practitioner"
    ) if ui_top_features else "General Practitioner"

    return {
        "probability": round(y_prob, 4),
        "prediction": y_pred,
        "risk_band": risk_band,
        "top_features": ui_top_features,
        "specialist_recommendation": specialist,
        "missing_labs": missing_labs,
    }


def _build_clinical_advice(top_features, current_probability, previous_probability, trend, enhance=True):
    """
    Computes the trend-aware clinical action plan for a given (already
    filtered) top-features list, and merges each feature's impact
    percentage directly onto its dict in place (adds "impact_pct"), so the
    list can be handed straight to the /predict JSON response.

    `enhance` controls whether get_clinical_advice() attempts the Grok
    rewrite (True, for the patient-facing UI) or uses only the raw
    AHA-aligned baseline text (False). See heartguard_knowledge's
    get_clinical_advice() and _fetch_grok_advice() for the fallback
    contract -- a Grok failure never surfaces here; it silently resolves
    to baseline text either way.

    Safe to call with an empty top_features list (e.g. after filtering, if
    nothing significant/modifiable remains): returns an empty action plan
    and still computes the trend sentence independently, since that only
    depends on the two probabilities, not on any feature list.

    Returns: (action_plan dict, trend_summary string-or-None)
    """
    advice_result = get_clinical_advice(
        top_features=top_features,
        trend=trend,
        current_probability=current_probability,
        previous_probability=previous_probability,
        enhance=enhance,
    )
    impact_map = advice_result["impact"]
    for f in top_features:
        f["impact_pct"] = impact_map.get(f["feature"], 0.0)
        f.pop("value", None)

    trend_summary = get_risk_trend_sentiment(current_probability, previous_probability)
    return advice_result["advice"], trend_summary


def _build_prediction_response(result, patient_id, trend, trend_summary, action_plan):
    """
    Shapes a single scored record into the JSON payload returned by
    /predict: the UI-relevant fields (probability, risk_band,
    trend_summary, and the impact/explanation-annotated top_features list)
    plus the supporting fields the UI also needs (specialist
    recommendation, missing labs, the raw prediction/threshold, and the
    action plan text).
    """
    return {
        "patient_id": patient_id,
        "probability": result["probability"],
        "prediction": result["prediction"],
        "risk_band": result["risk_band"],
        "trend": trend,
        "trend_summary": trend_summary,
        "top_features": result["top_features"],
        "action_plan": action_plan,
        "specialist_recommendation": result["specialist_recommendation"],
        "missing_labs": result["missing_labs"],
    }


@app.route("/predict", methods=["POST"])
def predict():
    payload = request.get_json(force=True)
    if request.args.get("patient_id"):
        patient_id = request.args.get("patient_id")
    elif isinstance(payload, dict) and "patient_id" in payload:
        patient_id = payload["patient_id"]
    else:
        patient_id = "anonymous"

    try:
        input_df, _ = _prepare_input(payload)
    except ValueError as exc:
        return jsonify({"error": str(exc)}), 400

    results = []
    for i in range(len(input_df)):
        row_df = input_df.iloc[[i]]

        # Fetch history BEFORE saving this row's prediction, so
        # previous_probability reflects the last *stored* assessment and is
        # never contaminated by the prediction we're about to save. This
        # also correctly chains across rows within the same batch request,
        # since each iteration's save is visible to the next iteration's
        # lookup.
        previous_probability = _get_previous_probability(patient_id)

        result = _score_single(row_df)
        db.save_prediction(patient_id, result["probability"], result["risk_band"])
        trend = db.get_trend(patient_id)

        # UI response only ever sees the capped, filtered "top_features"
        # list -- impact percentages are computed relative to that list.
        # enhance=True: the patient-facing UI gets the Grok-rewritten
        # advice when available, silently falling back to the raw AHA
        # baseline text if Grok is unavailable/fails.
        action_plan, trend_summary = _build_clinical_advice(
            result["top_features"], result["probability"], previous_probability, trend,
            enhance=True,
        )

        results.append(
            _build_prediction_response(result, patient_id, trend, trend_summary, action_plan)
        )

    return jsonify(results[0] if not isinstance(payload, list) else results)


@app.route("/history/<patient_id>", methods=["GET"])
def history(patient_id):
    return jsonify({
        "patient_id": patient_id,
        "history": db.get_history(patient_id),
        "trend": db.get_trend(patient_id),
    })


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
